# Generated by Django 4.1.2 on 2022-10-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingforms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthplanpatient',
            name='outreach',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Outreach Name'),
        ),
    ]
