# Generated by Django 4.1.2 on 2022-10-27 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingforms', '0003_outreachpatient_outreachpatientcalldetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutreachAppointmentLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Location')),
                ('slot_created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Slot Created By')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Outreach Appointment Location',
                'verbose_name_plural': 'Outreach Appointment Location',
            },
        ),
        migrations.CreateModel(
            name='OutreachAppointmentTiming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('time', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time')),
                ('maximum_booking_per_slot', models.IntegerField(blank=True, null=True, verbose_name='Maximum Booking Per Slot')),
                ('slot_created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Slot Created By')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingforms.outreachappointmentlocation')),
            ],
            options={
                'verbose_name': 'Outreach Appointment Timing',
                'verbose_name_plural': 'Outreach Appointment Timing',
            },
        ),
    ]
