# Generated by Django 4.1.2 on 2022-10-28 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingforms', '0004_outreachappointmentlocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreachappointmentlocation',
            name='outreach',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Outreach'),
        ),
        migrations.AddField(
            model_name='outreachappointmenttiming',
            name='outreach',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Outreach'),
        ),
    ]
