# Generated by Django 4.1.2 on 2022-11-01 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingforms', '0006_remove_outreachappointmenttiming_location_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPTable',
        ),
    ]
