# Generated by Django 4.1.2 on 2023-10-31 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberConsent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Member Consent',
                'verbose_name_plural': 'Member Consents',
            },
        ),
        migrations.CreateModel(
            name='MemberPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=50, null=True, verbose_name='Identifier')),
                ('identifier_system', models.CharField(blank=True, max_length=50, null=True, verbose_name='Identifier System')),
                ('active', models.BooleanField(blank=True, null=True, verbose_name='Active')),
                ('name_given', models.CharField(blank=True, max_length=100, null=True, verbose_name='Given Name')),
                ('name_family', models.CharField(blank=True, max_length=100, null=True, verbose_name='Family Name')),
                ('name_prefix', models.CharField(blank=True, max_length=100, null=True, verbose_name='Prefix Name')),
                ('name_suffix', models.CharField(blank=True, max_length=100, null=True, verbose_name='Suffix Name')),
                ('contact_value', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Value')),
                ('contact_use', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Use')),
                ('gender', models.CharField(blank=True, max_length=100, null=True, verbose_name='Gender')),
                ('birthDate', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('preferred_language', models.CharField(blank=True, max_length=100, null=True, verbose_name='Preferred Language')),
                ('address_use', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Use')),
                ('address_line', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Line')),
                ('address_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address City')),
                ('address_district', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address District')),
                ('address_state', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address State')),
                ('address_postalCode', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Zip')),
                ('address_country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Country')),
                ('photo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Photo')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Member Patient',
                'verbose_name_plural': 'Member Patients',
            },
        ),
        migrations.CreateModel(
            name='TenantMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.memberpatient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.client')),
            ],
            options={
                'verbose_name': 'Tenant Member',
                'verbose_name_plural': 'Tenant Members',
            },
        ),
        migrations.CreateModel(
            name='MemberConsentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_status', models.BooleanField(blank=True, null=True, verbose_name='Consent Status')),
                ('consent_duration', models.DateField(blank=True, null=True, verbose_name='Consent Duration')),
                ('purpose_of_data_sharing', models.CharField(blank=True, max_length=100, null=True, verbose_name='Purpose of Data Sharing')),
                ('sharing_with_provider', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sharing with Provider')),
                ('sharing_for_research', models.BooleanField(blank=True, null=True, verbose_name='Sharing for Research')),
                ('consent_notify', models.BooleanField(blank=True, null=True, verbose_name='Consent Notify')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Created By')),
                ('active', models.BooleanField(blank=True, null=True, verbose_name='Active')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('member_consent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.memberconsent')),
            ],
            options={
                'verbose_name': 'Member Consent Histroy',
                'verbose_name_plural': 'Member Consent History',
            },
        ),
        migrations.AddField(
            model_name='memberconsent',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.memberpatient'),
        ),
        migrations.AddField(
            model_name='memberconsent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.client'),
        ),
    ]
