# Generated by Django 4.1.2 on 2023-10-31 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_memberconsent_memberpatient_tenantmembers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberconsenthistory',
            name='revoked_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Revoked By'),
        ),
    ]
