# Generated by Django 4.1.2 on 2023-01-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='appaccessdata',
            name='action',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='action'),
        ),
    ]
