# Generated by Django 4.1.2 on 2023-01-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_appaccessdata_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='app_logo',
            field=models.FileField(blank=True, default='phone.png', null=True, upload_to='media/uploads/na3ohXaeOhleeng7/', verbose_name='App Logo'),
        ),
    ]
