# Generated by Django 4.1.2 on 2023-02-10 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_apps_app_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(max_length=100, verbose_name='Quality')),
                ('report_type', models.CharField(max_length=100, verbose_name='Report Type')),
            ],
        ),
    ]
