# Generated by Django 4.1.2 on 2023-02-10 13:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_qualityservices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualityservices',
            name='report_type',
        ),
        migrations.AddField(
            model_name='qualityservices',
            name='field_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Field Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qualityservices',
            name='field_value',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Field Value'),
            preserve_default=False,
        ),
    ]
