# Generated by Django 4.1.2 on 2023-02-27 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_remove_qualityservices_report_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(choices=[('text', 'Text Field'), ('email', 'Email Field'), ('number', 'Number Field'), ('checkbox', 'Checkbox Field'), ('radio', 'Radio Field'), ('select', 'Select Field'), ('textarea', 'Textarea Field'), ('date', 'Date Field')], max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='mainapp.form')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
