# Generated by Django 4.1.2 on 2023-02-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_field_option_1_field_option_10_field_option_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='option_1',
        ),
        migrations.RemoveField(
            model_name='field',
            name='option_10',
        ),
        migrations.RemoveField(
            model_name='field',
            name='option_2',
        ),
        migrations.RemoveField(
            model_name='field',
            name='option_3',
        ),
        migrations.RemoveField(
            model_name='field',
            name='option_4',
        ),
        migrations.RemoveField(
            model_name='field',
            name='option_5',
        ),
        migrations.RemoveField(
            model_name='field',
            name='option_6',
        ),
        migrations.RemoveField(
            model_name='field',
            name='option_7',
        ),
        migrations.RemoveField(
            model_name='field',
            name='option_8',
        ),
        migrations.RemoveField(
            model_name='field',
            name='option_9',
        ),
        migrations.AddField(
            model_name='field',
            name='options',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
