# Generated by Django 4.1.2 on 2023-02-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_remove_field_option_1_remove_field_option_10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.CharField(max_length=255),
        ),
    ]
