# Generated by Django 4.1.2 on 2023-02-28 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_field_field_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=100)),
                ('form_data', models.JSONField()),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
