# Generated by Django 4.1.2 on 2023-02-28 11:18

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_formsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequiredFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_columns', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250, null=True, verbose_name='All columns'), blank=True, null=True, size=50)),
                ('required_columns', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Required columns'), blank=True, null=True, size=50)),
                ('app_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.apps')),
            ],
        ),
    ]
