# Generated by Django 4.1.2 on 2023-01-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0003_ingressblob'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=50, null=True, verbose_name='Identifier')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('telecom', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telecom')),
                ('birthDate', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('status', models.BooleanField(blank=True, default=False, null=True, verbose_name='Status')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Member Patient',
                'verbose_name_plural': 'Member Patients',
            },
        ),
    ]
