# Generated by Django 4.1.2 on 2023-01-09 10:58

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0004_memberpatient'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreachpatient',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active ?'),
        ),
        migrations.AddField(
            model_name='outreachpatient',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='outreach.memberpatient'),
        ),
        migrations.AlterField(
            model_name='outreachpatient',
            name='outreach',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='outreach.outreachlist'),
        ),
        migrations.AlterField(
            model_name='outreachpatientcalldetails',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outreach.outreachpatient'),
        ),
        migrations.CreateModel(
            name='OutreachFilters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_filter_added', models.BooleanField(default=False, verbose_name='Filters Added ?')),
                ('age', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Age Range List'), size=30)),
                ('zipcode', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Zipcode List'), size=30)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('outreach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outreach.outreachlist')),
            ],
        ),
    ]
