# Generated by Django 4.1.2 on 2023-01-10 08:25

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0006_delete_ingressblob_remove_outreachfilters_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreachlist',
            name='age_from',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250, null=True, verbose_name='From Age List'), default=[1], size=30),
        ),
        migrations.AddField(
            model_name='outreachlist',
            name='age_to',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250, null=True, verbose_name='To Age List'), default=[1], size=30),
        ),
        migrations.AddField(
            model_name='outreachlist',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outreachlist',
            name='is_filter_added',
            field=models.BooleanField(default=False, verbose_name='Filters Added ?'),
        ),
        migrations.AddField(
            model_name='outreachlist',
            name='modified_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='outreachlist',
            name='zipcode',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Zipcode List'), default=[1], size=30),
        ),
        migrations.DeleteModel(
            name='OutreachFilters',
        ),
    ]
