# Generated by Django 4.1.2 on 2023-01-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0007_outreachlist_age_from_outreachlist_age_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreachlist',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Outreach Published ?'),
        ),
    ]
