# Generated by Django 4.1.2 on 2023-01-19 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0010_alter_outreachappointmenttiming_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outreachpatient',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outreach.memberpatient'),
        ),
    ]
