# Generated by Django 4.1.2 on 2023-01-27 11:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0011_alter_outreachpatient_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreachlist',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Notification End Date'),
        ),
        migrations.AddField(
            model_name='outreachlist',
            name='meridiem_type',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Meridiem Type'),
        ),
        migrations.AddField(
            model_name='outreachlist',
            name='notification_enabled',
            field=models.BooleanField(default=False, verbose_name='Outreach Notification enabled ?'),
        ),
        migrations.AddField(
            model_name='outreachlist',
            name='schedule_type',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Schedule Type'),
        ),
        migrations.AddField(
            model_name='outreachlist',
            name='scheduled_hours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Scheduled Hours'), default=[1], size=30),
        ),
        migrations.AddField(
            model_name='outreachlist',
            name='scheduled_minutes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Scheduled Minutes'), default=[1], size=30),
        ),
        migrations.AddField(
            model_name='outreachlist',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Notification Start Date'),
        ),
        migrations.AddField(
            model_name='outreachlist',
            name='weekdays',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Selected Days'), default=[1], size=30),
        ),
    ]
