# Generated by Django 4.1.2 on 2023-01-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0012_outreachlist_end_date_outreachlist_meridiem_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreachlist',
            name='notification_text',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Notification Text'),
        ),
    ]
