# Generated by Django 4.1.2 on 2023-01-31 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0013_outreachlist_notification_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreachlist',
            name='schedule_id',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Schedule ID'),
        ),
    ]
