# Generated by Django 4.1.2 on 2023-02-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0014_outreachlist_schedule_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberpatient',
            name='name',
        ),
        migrations.RemoveField(
            model_name='memberpatient',
            name='status',
        ),
        migrations.RemoveField(
            model_name='memberpatient',
            name='telecom',
        ),
        migrations.AddField(
            model_name='memberpatient',
            name='active',
            field=models.BooleanField(blank=True, null=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='memberpatient',
            name='address_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address City'),
        ),
        migrations.AddField(
            model_name='memberpatient',
            name='address_country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Country'),
        ),
        migrations.AddField(
            model_name='memberpatient',
            name='address_district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address District'),
        ),
        migrations.AddField(
            model_name='memberpatient',
            name='address_line',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Line'),
        ),
        migrations.AddField(
            model_name='memberpatient',
            name='address_postalCode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Zip'),
        ),
        migrations.AddField(
            model_name='memberpatient',
            name='address_state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address State'),
        ),
        migrations.AddField(
            model_name='memberpatient',
            name='address_use',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Use'),
        ),
        migrations.AddField(
            model_name='memberpatient',
            name='contact_use',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Use'),
        ),
        migrations.AddField(
            model_name='memberpatient',
            name='contact_value',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Value'),
        ),
        migrations.AddField(
            model_name='memberpatient',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='memberpatient',
            name='identifier_system',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Identifier System'),
        ),
        migrations.AddField(
            model_name='memberpatient',
            name='name_family',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Family Name'),
        ),
        migrations.AddField(
            model_name='memberpatient',
            name='name_given',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Given Name'),
        ),
        migrations.AddField(
            model_name='memberpatient',
            name='name_prefix',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Prefix Name'),
        ),
        migrations.AddField(
            model_name='memberpatient',
            name='name_suffix',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Suffix Name'),
        ),
        migrations.AddField(
            model_name='memberpatient',
            name='photo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Photo'),
        ),
    ]
