# Generated by Django 4.1.2 on 2023-02-20 10:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0015_remove_memberpatient_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreachlist',
            name='gender_filters',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Gender List'), default=[1], size=30),
        ),
    ]
