# Generated by Django 4.1.2 on 2023-10-31 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_memberconsent_memberpatient_tenantmembers_and_more'),
        ('outreach', '0016_outreachlist_gender_filters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outreachpatient',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.memberpatient'),
        ),
        migrations.DeleteModel(
            name='MemberPatient',
        ),
    ]
