# Generated by Django 3.1.5 on 2022-09-19 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Patient First Name')),
                ('patient_last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Patient Last Name')),
                ('date_of_event', models.DateField(blank=True, null=True, verbose_name='Date Of Event')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date Of Birth')),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone Number')),
                ('who_was_involoved', models.CharField(blank=True, max_length=100, null=True, verbose_name='Who Was Involved')),
                ('report_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Report Type')),
                ('service_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Service Type')),
                ('site', models.CharField(blank=True, max_length=100, null=True, verbose_name='Site')),
                ('county', models.CharField(blank=True, max_length=100, null=True, verbose_name='County')),
                ('event_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Event type')),
                ('provider_mentioned', models.CharField(blank=True, max_length=100, null=True, verbose_name='Provider mentioned')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('steps_taken_to_resolve_this_issue', models.TextField(blank=True, null=True, verbose_name='Steps Taken to resolve this issue')),
                ('outcome_resolution', models.TextField(blank=True, null=True, verbose_name='Outcome/Resolution')),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Resolved By')),
                ('resolving_comments', models.TextField(blank=True, null=True, verbose_name='Resolving Comments')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Created By')),
                ('file_1', models.FileField(blank=True, null=True, upload_to='media/uploads/na3ohXaeOhleeng7/', verbose_name='File 1')),
                ('file_2', models.FileField(blank=True, null=True, upload_to='media/uploads/na3ohXaeOhleeng7/', verbose_name='File 2')),
                ('file_3', models.FileField(blank=True, null=True, upload_to='media/uploads/na3ohXaeOhleeng7/', verbose_name='File 3')),
                ('file_4', models.FileField(blank=True, null=True, upload_to='media/uploads/na3ohXaeOhleeng7/', verbose_name='File 4')),
                ('file_5', models.FileField(blank=True, null=True, upload_to='media/uploads/na3ohXaeOhleeng7/', verbose_name='File 5')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Compliance',
                'verbose_name_plural': 'Compliances',
            },
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=20, verbose_name='App Name')),
                ('county', models.CharField(max_length=20, verbose_name='County')),
            ],
        ),
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Patient First Name')),
                ('patient_last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Patient Last Name')),
                ('date_of_event', models.DateField(blank=True, null=True, verbose_name='Date Of Event')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date Of Birth')),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone Number')),
                ('who_was_involoved', models.CharField(blank=True, max_length=100, null=True, verbose_name='Who Was Involved')),
                ('grievance_report_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Grievance Report Type')),
                ('service_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Service Type')),
                ('site', models.CharField(blank=True, max_length=100, null=True, verbose_name='Site')),
                ('county', models.CharField(blank=True, max_length=100, null=True, verbose_name='County')),
                ('event_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Event type')),
                ('health_plan', models.CharField(blank=True, max_length=100, null=True, verbose_name='Health plan')),
                ('provider_mentioned', models.CharField(blank=True, max_length=100, null=True, verbose_name='Provider mentioned')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('steps_taken_to_resolve_this_issue', models.TextField(blank=True, null=True, verbose_name='Steps Taken to resolve this issue')),
                ('outcome_resolution', models.TextField(blank=True, null=True, verbose_name='Outcome/Resolution')),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Resolved By')),
                ('resolving_comments', models.TextField(blank=True, null=True, verbose_name='Resolving Comments')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Created By')),
                ('file_1', models.FileField(blank=True, null=True, upload_to='media/uploads/na3ohXaeOhleeng7/', verbose_name='File 1')),
                ('file_2', models.FileField(blank=True, null=True, upload_to='media/uploads/na3ohXaeOhleeng7/', verbose_name='File 2')),
                ('file_3', models.FileField(blank=True, null=True, upload_to='media/uploads/na3ohXaeOhleeng7/', verbose_name='File 3')),
                ('file_4', models.FileField(blank=True, null=True, upload_to='media/uploads/na3ohXaeOhleeng7/', verbose_name='File 4')),
                ('file_5', models.FileField(blank=True, null=True, upload_to='media/uploads/na3ohXaeOhleeng7/', verbose_name='File 5')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grievance',
                'verbose_name_plural': 'Grievances',
            },
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_signed_date', models.DateField(blank=True, null=True, verbose_name='Letter Signed Date')),
                ('letter_sent_date', models.DateField(blank=True, null=True, verbose_name='Letter Sent Date')),
                ('service_line', models.CharField(blank=True, max_length=100, null=True, verbose_name='Service Line')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name')),
                ('mrn', models.CharField(blank=True, max_length=100, null=True, verbose_name='MRN')),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone Number')),
                ('scanned_date', models.DateField(blank=True, max_length=100, null=True, verbose_name='Scanned Date')),
                ('county', models.CharField(blank=True, max_length=100, null=True, verbose_name='County')),
                ('location_site', models.CharField(blank=True, max_length=100, null=True, verbose_name='Location/Site')),
                ('ethnicity_race', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ethnicity/Race')),
                ('severity', models.CharField(blank=True, max_length=100, null=True, verbose_name='Severity')),
                ('level_of_intervention', models.CharField(blank=True, max_length=100, null=True, verbose_name='Level of Intervention')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Is Resolved?')),
                ('resolved_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Resolved By')),
                ('resolving_comments', models.TextField(blank=True, null=True, verbose_name='Resolving Comments')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Created By')),
                ('file_1', models.FileField(blank=True, null=True, upload_to='media/uploads/na3ohXaeOhleeng7/', verbose_name='File 1')),
                ('file_2', models.FileField(blank=True, null=True, upload_to='media/uploads/na3ohXaeOhleeng7/', verbose_name='File 2')),
                ('file_3', models.FileField(blank=True, null=True, upload_to='media/uploads/na3ohXaeOhleeng7/', verbose_name='File 3')),
                ('file_4', models.FileField(blank=True, null=True, upload_to='media/uploads/na3ohXaeOhleeng7/', verbose_name='File 4')),
                ('file_5', models.FileField(blank=True, null=True, upload_to='media/uploads/na3ohXaeOhleeng7/', verbose_name='File 5')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Incident Report',
                'verbose_name_plural': 'Incident Reports',
            },
        ),
        migrations.CreateModel(
            name='MultipleCommentsIncidentReporting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiple_comments', models.TextField(blank=True, max_length=100, null=True, verbose_name='Multiple Comment')),
                ('staff', models.CharField(blank=True, max_length=100, null=True, verbose_name='Staff')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grievanceapp.incidentreport')),
            ],
            options={
                'verbose_name': 'Indicent Report Comment',
                'verbose_name_plural': 'Indicent Report Comments',
            },
        ),
        migrations.CreateModel(
            name='MultipleCommentsCompliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiple_comments', models.TextField(blank=True, max_length=100, null=True, verbose_name='Multiple Comment')),
                ('staff', models.CharField(blank=True, max_length=100, null=True, verbose_name='Staff')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grievanceapp.compliance')),
            ],
            options={
                'verbose_name': 'Compliance Comment',
                'verbose_name_plural': 'Compliance Comments',
            },
        ),
        migrations.CreateModel(
            name='MultipleComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiple_comments', models.TextField(blank=True, max_length=100, null=True, verbose_name='Multiple Comment')),
                ('staff', models.CharField(blank=True, max_length=100, null=True, verbose_name='Staff')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grievanceapp.grievance')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grievanceapp.county')),
            ],
        ),
    ]
