# Generated by Django 4.1.2 on 2023-02-21 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covidtestlogin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeVaccination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_proof_or_vaccination_copy_provided', models.BooleanField(blank=True, null=True, verbose_name='Is Proof Or Vaccination Copy Provided?')),
                ('allow_csv_to_pull_record', models.BooleanField(blank=True, null=True, verbose_name='Allow CSV To Pull EPIC Medical Record Or CAIR record')),
                ('is_vaccine_declined', models.BooleanField(blank=True, null=True, verbose_name='Vaccination Declined?')),
                ('file_1', models.FileField(blank=True, null=True, upload_to='media/uploads/na3ohXaeOhleeng7/', verbose_name='File 1')),
                ('file_1_status', models.BooleanField(blank=True, null=True, verbose_name='File 1 Status')),
                ('file_2', models.FileField(blank=True, null=True, upload_to='media/uploads/na3ohXaeOhleeng7/', verbose_name='File 2')),
                ('file_2_status', models.BooleanField(blank=True, null=True, verbose_name='File 2 Status')),
                ('signature_data', models.TextField(blank=True, null=True, verbose_name='Signature')),
                ('is_verified_by_staff', models.BooleanField(blank=True, default=False, null=True, verbose_name='Is verified by staff')),
                ('user_submission_datetime', models.DateTimeField(blank=True, null=True, verbose_name='User Submission Date Time')),
            ],
        ),
        migrations.CreateModel(
            name='VaccineManagementList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('is_published', models.BooleanField(default=True, verbose_name='Is Published ?')),
                ('created_by', models.CharField(max_length=80, verbose_name='Created By')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vaccine Management List',
                'verbose_name_plural': 'Vaccine Management Lists',
            },
        ),
        migrations.DeleteModel(
            name='OTPTable',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='allow_csv_to_pull_record',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='allow_csv_to_pull_record_verified',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='epic_medical_fully_vaccinated_test_until_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='epic_medical_loa_until',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='epic_medical_second_dose_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='file_1',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='file_1_status',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='file_2',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='file_2_status',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='file_3',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='file_3_status',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='file_4',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='file_4_status',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='file_5',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='file_5_status',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='file_6',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='file_6_status',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='file_7',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='file_7_status',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_proof_or_vaccination_copy_provided',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_vaccine_declined',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='signature_data',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user_submission_datetime',
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='employeevaccination',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covidtestlogin.employee'),
        ),
        migrations.AddField(
            model_name='employeevaccination',
            name='vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covidtestlogin.vaccinemanagementlist'),
        ),
    ]
