# Generated by Django 4.1.2 on 2023-02-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidtestlogin', '0002_employeevaccination_vaccinemanagementlist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeevaccination',
            name='is_verified_by_staff',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is verified by staff'),
        ),
    ]
