# Generated by Django 4.1.2 on 2023-03-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidtestlogin', '0003_alter_employeevaccination_is_verified_by_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeevaccination',
            name='is_verified_by_staff',
        ),
        migrations.AddField(
            model_name='employeevaccination',
            name='is_approved_by_staff',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is Approved by staff'),
        ),
    ]
