# Generated by Django 4.1.2 on 2023-03-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidtestlogin', '0003_alter_employeevaccination_is_verified_by_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinemanagementlist',
            name='acknowledgement_text',
            field=models.TextField(blank=True, null=True, verbose_name='Acknowledgement Text'),
        ),
        migrations.AddField(
            model_name='vaccinemanagementlist',
            name='acknowledgement_title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Acknowledgement Title'),
        ),
    ]
