# Generated by Django 4.1.2 on 2023-03-01 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidtestlogin', '0004_remove_employeevaccination_is_verified_by_staff_and_more'),
        ('covidtestlogin', '0004_vaccinemanagementlist_acknowledgement_text_and_more'),
    ]

    operations = [
    ]
