# Generated by Django 4.1.2 on 2023-03-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidtestlogin', '0005_merge_20230301_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeevaccination',
            name='file_3',
            field=models.FileField(blank=True, null=True, upload_to='media/uploads/na3ohXaeOhleeng7/', verbose_name='File 3'),
        ),
        migrations.AddField(
            model_name='employeevaccination',
            name='file_3_status',
            field=models.BooleanField(blank=True, null=True, verbose_name='File 3 Status'),
        ),
        migrations.AddField(
            model_name='vaccinemanagementlist',
            name='file_format',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='File Format'),
        ),
        migrations.AddField(
            model_name='vaccinemanagementlist',
            name='max_file_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maximum File Size'),
        ),
        migrations.AddField(
            model_name='vaccinemanagementlist',
            name='max_file_upload',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maximum File Upload'),
        ),
    ]
