# Generated by Django 4.1.2 on 2023-03-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidtestlogin', '0006_employeevaccination_file_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinemanagementlist',
            name='checkbox_one_file_upload',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Checkbox One File Upload'),
        ),
        migrations.AddField(
            model_name='vaccinemanagementlist',
            name='checkbox_one_text',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Checkbox One Text'),
        ),
        migrations.AddField(
            model_name='vaccinemanagementlist',
            name='checkbox_three_file_upload',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Checkbox Three File Upload'),
        ),
        migrations.AddField(
            model_name='vaccinemanagementlist',
            name='checkbox_three_text',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Checkbox Three Text'),
        ),
        migrations.AddField(
            model_name='vaccinemanagementlist',
            name='checkbox_two_file_upload',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Checkbox two File Upload'),
        ),
        migrations.AddField(
            model_name='vaccinemanagementlist',
            name='checkbox_two_text',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Checkbox Two Text'),
        ),
    ]
