# Generated by Django 4.1.2 on 2023-03-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidtestlogin', '0008_rename_file_format_vaccinemanagementlist_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccineexemption',
            name='file_4',
        ),
        migrations.RemoveField(
            model_name='vaccineexemption',
            name='file_4_status',
        ),
        migrations.RemoveField(
            model_name='vaccineexemption',
            name='file_5',
        ),
        migrations.RemoveField(
            model_name='vaccineexemption',
            name='file_5_status',
        ),
        migrations.RemoveField(
            model_name='vaccineexemption',
            name='file_6',
        ),
        migrations.RemoveField(
            model_name='vaccineexemption',
            name='file_6_status',
        ),
        migrations.RemoveField(
            model_name='vaccineexemption',
            name='file_7',
        ),
        migrations.RemoveField(
            model_name='vaccineexemption',
            name='file_7_status',
        ),
        migrations.RemoveField(
            model_name='vaccineexemption',
            name='religious_exemption_text',
        ),
        migrations.AddField(
            model_name='vaccineexemption',
            name='exemption_text',
            field=models.TextField(blank=True, null=True, verbose_name='Exemption Text'),
        ),
        migrations.AddField(
            model_name='vaccinemanagementlist',
            name='allow_exemption_submission',
            field=models.BooleanField(default=False, verbose_name='Allow Execmption Submission ?'),
        ),
        migrations.AddField(
            model_name='vaccinemanagementlist',
            name='is_file_upload_one_required',
            field=models.BooleanField(default=True, verbose_name='Is file upload one required'),
        ),
        migrations.AddField(
            model_name='vaccinemanagementlist',
            name='is_file_upload_three_required',
            field=models.BooleanField(default=True, verbose_name='Is file upload three required'),
        ),
        migrations.AddField(
            model_name='vaccinemanagementlist',
            name='is_file_upload_two_required',
            field=models.BooleanField(default=True, verbose_name='Is file upload two required'),
        ),
    ]
